services:
  web:
    build: .
    # Perintah paling andal untuk Gunicorn di produksi
    command: gunicorn --pythonpath /app mochafolk_backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    # Kita tidak menggunakan volume kode di produksi agar stabil
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      # --- Konfigurasi Keamanan & Domain ---
      - DJANGO_SECRET_KEY=2=ugfm6g+#=at=006_i8b@j9@7ey5+r8e6sq6ww$8p^_(m!2zn
      - DEBUG=False
      - ALLOWED_HOSTS=api.mochafolk.com,localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=https://app.mochafolk.com,http://localhost:3000
      - CSRF_TRUSTED_ORIGINS=https://api.mochafolk.com,https://app.mochafolk.com

      # --- Konfigurasi Database & Redis ---
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Lighthouse1717
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # --- Konfigurasi Layanan Pihak Ketiga ---
      - FRONTEND_URL=https://app.mochafolk.com
      - MIDTRANS_SERVER_KEY=Mid-server-qkjzSDQIaFiRUwlEk9XCBoSG # Ganti dengan kunci Midtrans Produksi Anda nanti
      - MIDTRANS_IS_PRODUCTION=False # Ganti menjadi True saat live
      - VAPID_PUBLIC_KEY=BJOXk4RvAyYTQQGseNXTiJHady-i9lePv8vUtBQlakN1J72oAfUzFFkU-3KWVpZ3tIP2InyRIu_NNBZ2hdeGlBA
      - VAPID_PRIVATE_KEY=O_sWGnmyHzxWJz8OZHyeq3eJaEDilVsalvDwAUSJj9U
      - WEBPUSH_EMAIL=mochafolk@gmail.com

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Lighthouse1717
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:
