# Generated by Django 5.2.4 on 2025-07-08 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('done', 'Done')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='shops.coffeeshop')),
            ],
            options={
                'unique_together': {('coffee_shop', 'queue_number', 'status')},
            },
        ),
    ]
