# Generated by Django 5.2.4 on 2025-07-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
