# Generated by Django 5.2.4 on 2025-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_queue_unique_together_alter_queue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
