# Generated by Django 5.2.4 on 2025-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_coffeeshop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='plan',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro')], default='BASIC', max_length=5),
        ),
    ]
